package com.moorhenapps.bluehex.utils

import android.graphics.Color
import com.moorhenapps.bluehex.R

enum class Colour constructor(val nameRes: Int, val useLightIcons: Boolean, vararg val colours: Int) {
    BLUE(R.string.blue, true,
            Color.parseColor("#239dce"),
            Color.parseColor("#1f8eb9"),
            Color.parseColor("#2298c6"),
            Color.parseColor("#59c2ee"),
            Color.parseColor("#0c88f4"),
            Color.parseColor("#1a76e1")),
    GREEN(R.string.green, true,
            Color.parseColor("#81C784"),
            Color.parseColor("#2E7D32"),
            Color.parseColor("#1B5E20"),
            Color.parseColor("#6D4C41"),
            Color.parseColor("#7CB342"),
            Color.parseColor("#558B2F")),
    GREY(R.string.grey, true,
            Color.parseColor("#555555"),
            Color.parseColor("#FFFFFF"),
            Color.parseColor("#000000"),
            Color.parseColor("#838383"),
            Color.parseColor("#AAAAAA"),
            Color.parseColor("#CCCCCC")),
    PURPLE(R.string.purple, true,
            Color.parseColor("#6A1B9A"),
            Color.parseColor("#9C27B0"),
            Color.parseColor("#7B1FA2"),
            Color.parseColor("#BA68C8"),
            Color.parseColor("#4A148C"),
            Color.parseColor("#6D2D78"),
            Color.parseColor("#AA00FF")),
    RED(R.string.red, true,
            Color.parseColor("#870923"),
            Color.parseColor("#BA3316"),
            Color.parseColor("#911B01"),
            Color.parseColor("#EC7358"),
            Color.parseColor("#ED1B0E"),
            Color.parseColor("#FF9F0C"),
            Color.parseColor("#FF5733")),
    NEXUS(R.string.nexus, true,
            Color.parseColor("#25ADFF"),
            Color.parseColor("#ffffff"),
            Color.parseColor("#FFC100"),
            Color.parseColor("#FF3800")),
    PINK(R.string.pink, false,
            Color.parseColor("#F62DAE"),
            Color.parseColor("#E0299F"),
            Color.parseColor("#B91793"),
            Color.parseColor("#A4036F"),
            Color.parseColor("#D30C7B")),
    PASTEL(R.string.pastel, true,
            Color.parseColor("#00040e"),
            Color.parseColor("#dab6c8"),
            Color.parseColor("#a6dcee"),
            Color.parseColor("#5389a6"),
            Color.parseColor("#e8ebea")),
    RAINBOW(R.string.rainbow, true,
            Color.parseColor("#9400D3"),
            Color.parseColor("#4B0082"),
            Color.parseColor("#0000FF"),
            Color.parseColor("#00FF00"),
            Color.parseColor("#FFFF00"),
            Color.parseColor("#FF7F00"),
            Color.parseColor("#FF0000")
    ),
    DARK(R.string.dark, true,
            Color.parseColor("#10102c"),
            Color.parseColor("#342c5c"),
            Color.parseColor("#67647d"),
            Color.parseColor("#272d50"),
            Color.parseColor("#bdc7d8")
    ),
    GOLD(R.string.gold, false,
            Color.parseColor("#b4a14f"),
            Color.parseColor("#ffda68"),
            Color.parseColor("#a98c46"),
            Color.parseColor("#fff381"),
            Color.parseColor("#ffd483")
    ),
    RETRO(R.string.retro, true,
            Color.parseColor("#66202a"),
            Color.parseColor("#c8783f"),
            Color.parseColor("#e1b878"),
            Color.parseColor("#75acc0")),

}