package com.moorhenapps.bluehex.utils

import android.graphics.Color
import com.moorhenapps.bluehex.R

enum class Colour constructor(val nameRes: Int, val useLightIcons: Boolean, vararg val colours: Int) {
    BLUE(R.string.blue, true,
            Color.parseColor("#239dce"),
            Color.parseColor("#1f8eb9"),
            Color.parseColor("#2298c6"),
            Color.parseColor("#59c2ee"),
            Color.parseColor("#0c88f4"),
            Color.parseColor("#1a76e1")),
    GREEN(R.string.green, true,
            Color.parseColor("#81C784"),
            Color.parseColor("#2E7D32"),
            Color.parseColor("#1B5E20"),
            Color.parseColor("#6D4C41"),
            Color.parseColor("#7CB342"),
            Color.parseColor("#558B2F")),
    GREY(R.string.grey, true,
            Color.parseColor("#555555"),
            Color.parseColor("#FFFFFF"),
            Color.parseColor("#000000"),
            Color.parseColor("#838383"),
            Color.parseColor("#AAAAAA"),
            Color.parseColor("#CCCCCC")),
    PURPLE(R.string.purple, true,
            Color.parseColor("#6A1B9A"),
            Color.parseColor("#9C27B0"),
            Color.parseColor("#7B1FA2"),
            Color.parseColor("#BA68C8"),
            Color.parseColor("#4A148C"),
            Color.parseColor("#6D2D78"),
            Color.parseColor("#AA00FF")),
    RED(R.string.red, true,
            Color.parseColor("#870923"),
            Color.parseColor("#BA3316"),
            Color.parseColor("#911B01"),
            Color.parseColor("#EC7358"),
            Color.parseColor("#ED1B0E"),
            Color.parseColor("#FF9F0C"),
            Color.parseColor("#FF5733")),
    NEXUS(R.string.nexus, true,
            Color.parseColor("#25ADFF"),
            Color.parseColor("#ffffff"),
            Color.parseColor("#FFC100"),
            Color.parseColor("#FF3800")),
    PINK(R.string.pink, false,
            Color.parseColor("#F62DAE"),
            Color.parseColor("#E0299F"),
            Color.parseColor("#B91793"),
            Color.parseColor("#A4036F"),
            Color.parseColor("#D30C7B")),
    PASTEL(R.string.pastel, true,
            Color.parseColor("#00040e"),
            Color.parseColor("#dab6c8"),
            Color.parseColor("#a6dcee"),
            Color.parseColor("#5389a6"),
            Color.parseColor("#e8ebea")),
    DARK(R.string.dark, true,
            Color.parseColor("#10102c"),
            Color.parseColor("#342c5c"),
            Color.parseColor("#67647d"),
            Color.parseColor("#272d50"),
            Color.parseColor("#bdc7d8")),
    GOLD(R.string.gold, false,
            Color.parseColor("#b4a14f"),
            Color.parseColor("#ffda68"),
            Color.parseColor("#a98c46"),
            Color.parseColor("#fff381"),
            Color.parseColor("#ffd483")),
    RETRO(R.string.retro, true,
            Color.parseColor("#66202a"),
            Color.parseColor("#c8783f"),
            Color.parseColor("#e1b878"),
            Color.parseColor("#75acc0")),
    RAINBOW(R.string.lgbt, true,
            Color.parseColor("#ff67b1"),
            Color.parseColor("#ff0010"),
            Color.parseColor("#ff8b26"),
            Color.parseColor("#fffd44"),
            Color.parseColor("#008e1f"),
            Color.parseColor("#00c1bf"),
            Color.parseColor("#3b0d94"),
            Color.parseColor("#90038b")),
    ASEXUAL(R.string.asex, true,
            Color.parseColor("#000000"),
            Color.parseColor("#a4a4a4"),
            Color.parseColor("#ffffff"),
            Color.parseColor("#83037e")),
    BISEXUAL(R.string.bisex, true,
            Color.parseColor("#d60270"),
            Color.parseColor("#9b4f96"),
            Color.parseColor("#0038a8")),
    PANSEXUAL(R.string.pansex, true,
            Color.parseColor("#ff0b8b"),
            Color.parseColor("#ffd739"),
            Color.parseColor("#00b5fb")),
    TRANS(R.string.trans, true,
            Color.parseColor("#45d1f8"),
            Color.parseColor("#f9aab9"),
            Color.parseColor("#ffffff")),
    NONBINARY(R.string.nonbinary, true,
            Color.parseColor("#fff34f"),
            Color.parseColor("#9c5cce"),
            Color.parseColor("#000000"),
            Color.parseColor("#ffffff"))
}